c_compiler_version:    # [ppc64le]
- '7'                  # [ppc64le]
cxx_compiler_version:  # [ppc64le]
- '7'                  # [ppc64le]
cuda_compiler_version: # [ppc64le]
- '10.2'               # [ppc64le]
